apiVersion: v1
kind: Pod
metadata:
  name: dummy-name
  namespace: data-platform
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: deploy
            operator: In
            values:
            - etl
  containers:
  - env:
    - name: CODEPACK_CONFIG_PATH
      value: /opt/codepack/config/codepack.ini
    - name: CODEPACK_LOG_DIR
      value: /opt/codepack/logs
    - name: AIRFLOW__CORE__EXECUTOR
      value: LocalExecutor
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          name: airflow-secret
          key: AIRFLOW_MYSQL
    image: dummy-image
    imagePullPolicy: IfNotPresent
    name: base
    volumeMounts:
    - mountPath: /opt/airflow/logs
      name: airflow-logs
    - mountPath: /opt/airflow/dags
      name: airflow-dags
      readOnly: true
    - mountPath: /opt/airflow/local-fs
      name: local-fs
    - mountPath: /opt/airflow/pod-templates
      name: pod-templates
    - mountPath: /opt/codepack/config
      name: codepack-config
    - mountPath: /opt/codepack/logs
      name: codepack-logs
  restartPolicy: Never
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
  serviceAccountName: data-engineer-sa
  volumes:
  - name: airflow-logs
    persistentVolumeClaim:
      claimName: airflow-logs-pvc
  - name: airflow-dags
    persistentVolumeClaim:
      claimName: airflow-dags-pvc
  - name: local-fs
    persistentVolumeClaim:
      claimName: local-fs-pvc
  - name: pod-templates
    persistentVolumeClaim:
      claimName: pod-templates-pvc
  - name: codepack-config
    persistentVolumeClaim:
      claimName: codepack-config-pvc
  - name: codepack-logs
    persistentVolumeClaim:
      claimName: codepack-logs-pvc
