apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-engineer-role
  namespace: data-platform
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["*"]
