apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-engineer-rolebinding
  namespace: data-platform
subjects:
- kind: ServiceAccount
  name: data-engineer-sa
  namespace: data-platform
roleRef:
  kind: Role
  name: data-engineer-role
  apiGroup: rbac.authorization.k8s.io
