apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-fs-pvc
  namespace: data-platform
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      name: local-fs-pv
