apiVersion: v1
kind: PersistentVolume
metadata:
  name: pod-templates-pv
  namespace: data-platform
  labels:
    name: pod-templates-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.2.15
    path: /data/data-platform/nfs/pod-templates
