apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-templates-pvc
  namespace: data-platform
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: pod-templates-pv
