apiVersion: v1
kind: Pod
metadata:
  name: dummy-name
  namespace: airflow
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: deploy
            operator: In
            values:
            - etl
  containers:
  - env:
    - name: AIRFLOW__CORE__EXECUTOR
      value: LocalExecutor
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          name: airflow-secret
          key: AIRFLOW_MYSQL
    image: dummy-image
    imagePullPolicy: IfNotPresent
    name: base
    volumeMounts:
    - mountPath: /opt/airflow/logs
      name: airflow-logs
    - mountPath: /opt/airflow/dags
      name: airflow-dags
      readOnly: true
    - mountPath: /opt/airflow/local
      name: airflow-local
  restartPolicy: Never
  securityContext:
    runAsUser: 50000
    fsGroup: 50000
  serviceAccountName: airflow-sa
  volumes:
  - name: airflow-logs
    persistentVolumeClaim:
      claimName: airflow-logs-pvc
  - name: airflow-dags
    persistentVolumeClaim:
      claimName: airflow-dags-pvc
  - name: airflow-local
    persistentVolumeClaim:
      claimName: airflow-local-pvc
