apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-local-pv
  namespace: spark
  labels:
    name: spark-local-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.2.15
    path: /data/kubernetes/spark-local
