apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pod-templates-pvc
  namespace: spark
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: spark-pod-templates-pv
