apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-notebook-pvc
  namespace: data-platform
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: jupyter-notebook-pv
