apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-logs-pvc
  namespace: data-platform
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      name: jupyter-logs-pv
