apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-pvc
  namespace: airflow
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      name: airflow-local-pv
