apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-plugins-pv
  namespace: airflow
  labels:
    name: airflow-plugins-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.2.15
    path: /data/kubernetes/airflow-plugins
