apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pod-templates-pvc
  namespace: airflow
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: airflow-pod-templates-pv
