apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: data-platform
data:
  AIRFLOW_MYSQL: bXlzcWwrbXlzcWxkYjovL2lobm9raW06bXlzcWxAMTAuMC4yLjE1OjMzMDYvYWlyZmxvdw==
  AIRFLOW__WEBSERVER__SECRET_KEY: YWlyZmxvdw==
