apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-service
  namespace: data-platform
  annotations:
    metallb.universe.tf/allow-shared-ip: 10.0.2.3
spec:
  selector:
    tier: airflow
    component: webserver
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer
  loadBalancerIP: 10.0.2.3
