apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  namespace: data-platform
  labels:
    name: airflow-dags-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.2.15
    path: /data/data-platform/nfs/airflow/dags
