apiVersion: v1
kind: Service
metadata:
  name: spark-worker-service
  namespace: spark
spec:
  selector:
    tier: spark
    component: worker
  ports:
  - protocol: TCP
    port: 30081
    targetPort: 8081
    nodePort: 30081
    name: webui
  type: LoadBalancer
  loadBalancerIP: 10.0.2.4
