apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spark-worker-hpa
  namespace: spark
spec:
  minReplicas: 4
  maxReplicas: 8
  targetCPUUtilizationPercentage: 90
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spark-worker
