apiVersion: v1
kind: PersistentVolume
metadata:
  name: codepack-config-pv
  namespace: data-platform
  labels:
    name: codepack-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.2.15
    path: /data/data-platform/nfs/codepack/config
